# Generated by Django 4.1.6 on 2023-02-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='products_product: name must be unique!',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('sku',), name='products_product: sku must be unique!'),
        ),
    ]
