# Generated by Django 4.1.6 on 2023-02-17 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0001_initial'),
        ('products', '0003_productcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Products Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, db_column='manufacturer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='manufacturers.manufacturer', verbose_name='Manufacturer'),
        ),
    ]
